site_name: IT-Basis - Überblick über das Web und Programmiersprachen

nav:
  - Übersicht: index.md
  - HTML CSS:
    - Einführung: content/HTML_CSS/1.md
    - HTML-Elemente: content/HTML_CSS/2.md
    - Attribute & Formulare: content/HTML_CSS/3.md
    - CSS Fundamentals: content/HTML_CSS/4.md
    - CSS Layout: content/HTML_CSS/5.md
    - Accessibility: content/HTML_CSS/6.md
  - JavaScript:
    - Variablen & Operatoren: content/JavaScript/1.md
    - Kontrollstrukturen: content/JavaScript/2.md
    - DOM & Events: content/JavaScript/3.md
    - Async & APIs: content/JavaScript/4.md
  - XML:
    - Syntax & Struktur: content/XML/1.md
    - DTD & Schema: content/XML/2.md
    - XPath & XSLT: content/XML/3.md
  - Java Grundlagen:
    - Setup & Syntax: content/Java_Grundlagen/1.md
    - Kontrollstrukturen: content/Java_Grundlagen/2.md
  - Java Aufbau:
    - Streams & Lambdas: content/Java_Aufbau/1.md
    - Collections: content/Java_Aufbau/2.md
  - Application Server:
    - Einführung: content/Application_Server/1.md
    - Konfiguration: content/Application_Server/2.md
  - Low Code:
    - Einführung: content/Low_Code/1.md
    - Advanced: content/Low_Code/2.md


theme:
  name: material
  palette:
    primary: blue
    accent: green
    # primary: amber
    # accent: deep orange
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - navigation.tracking
    - navigation.path
    - navigation.top
    - navigation.footer
    - toc.follow
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - pymdownx.keys
  - admonition
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - toc:
      permalink: true
      toc_depth: 2
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: true

extra_css:
  - stylesheets/logo.css
  - stylesheets/grid.css
  - stylesheets/video_admonition.css
  - stylesheets/python_tutor_admonition.css
  - stylesheets/mermaid.css
  - stylesheets/cd.css

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
  
plugins:
    - search
    - macros

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://www.foerde-campus.de/

watch:
  - tasks

copyright: Copyright &copy; 2026 Qualidy GmbH